source 'https://rubygems.org'
ruby '2.2.2'

gem 'rails', '4.2.3'

gem 'active_model_serializers', github: 'rails-api/active_model_serializers'

gem 'responders'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
gem 'unicorn'

gem 'rack-cors', require: 'rack/cors'
# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
gem 'devise'
gem 'cancancan'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'jquery-rails'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'turbolinks'
gem 'simple_form'
gem 'slim-rails'


group :production do
  gem 'pg'
  gem 'rails_12factor'
end

group :development, :test do
  gem 'sqlite3'
  gem 'fuubar'
  gem 'pry'
  gem 'rspec-rails'
  gem 'shoulda-matchers', git: 'git://github.com/thoughtbot/shoulda-matchers.git'
  gem 'shoulda-callback-matchers', '~> 1.1.1'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'factory_girl_rails'

  gem 'pry-byebug'
end
